name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
      
      - name: Setup public directory
        run: |
          mkdir -p public/assets/Background/nature_5
          mkdir -p public/assets/1\ Pink_Monster
          mkdir -p public/assets/Menu
          cp -r assets/Background/nature_5/* public/assets/Background/nature_5/
          cp -r assets/1\ Pink_Monster/* public/assets/1\ Pink_Monster/
          cp -r assets/Menu/* public/assets/Menu/
      
      - name: Build
        run: |
          chmod +x node_modules/.bin/vite
          npm run build
      
      - name: List dist directory
        run: |
          echo "Contents of dist directory:"
          ls -R dist/
      
      - name: Create .nojekyll file
        run: touch ./dist/.nojekyll
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true